// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvwzwlcupkybptuhbuha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2d3p3bGN1cGt5YnB0dWhidWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjQ5NjMsImV4cCI6MjA2Mzk0MDk2M30.CKrDRwuQvU9orqGzAwauBEL3UNCS2X6TA5gtr2GjQQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);